spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
server:
  port: ${PORT}
endpoints:
  sensitive: false

occupancy:
  rnoc:
    places-api: https://m.gatech.edu/api/gtplaces
    wifi-api: http://wifi.dssg.rnoc.gatech.edu:8080/api/count
